[package]
name = "hv1-boot"
version.workspace = true
edition = "2024"  # Requires nightly Rust
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "HyperMachine Type-1 Hypervisor Bootable Image"

[[bin]]
name = "hv1"
path = "src/main.rs"

[dependencies]
hv1-core = { path = "../hv1-core", features = ["intel", "amd", "serial"] }
bootloader_api = "0.11"
x86_64 = "0.15"
linked_list_allocator = "0.10"
log = "0.4"

[build-dependencies]
bootloader = "0.11"

[features]
default = ["intel", "amd"]
intel = []
amd = []