[package]
name = "hv2-cpu"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
keywords.workspace = true
categories.workspace = true
description = "HyperMachine CPU virtualization and instruction decoding"

[dependencies]
hv2-core = { path = "../hv2-core", version = "1.1.0" }

anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true

[[example]]
name = "instruction_test"
path = "examples/instruction_test.rs"
