//! A real implementation of envd's `filesystem.Filesystem` gRPC service,
//! against the actual proto copied from `e2b-dev/runtime`'s
//! `packages/envd/spec/filesystem/filesystem.proto` (see
//! `proto/filesystem.proto`).
//!
//! # How this is implemented, and why it's honest about the cost
//!
//! `AgentVM` has no direct file-read/stat/list primitive -- only
//! `exec_in_guest`. So every RPC here shells out to a real coreutils/busybox
//! command inside the guest and parses its output, the same way a human at
//! a terminal would find this information, rather than a purpose-built
//! wire operation. That is slower (one or two guest round trips per call)
//! and more fragile (it depends on `stat -c`/`readlink`/`find` existing and
//! behaving as expected in whatever guest image is booted) than a real
//! envd's direct syscalls, but it is real: the reported size, owner,
//! permissions and modification time come from the guest's actual
//! filesystem, not fabricated.
//!
//! # What's implemented and what isn't
//!
//! `Stat`, `MakeDir`, `Move`, `ListDir`, `Remove` -- all real, all exec
//! into the guest. `WatchDir`/`CreateWatcher`/`GetWatcherEvents`/
//! `RemoveWatcher` are `unimplemented`: watching needs a long-lived guest
//! process reporting back over a channel this design doesn't have yet.
//! `EntryInfo::metadata` (xattr-derived, per the proto's own comment) is
//! always empty -- reading `user.e2b.*` xattrs would need another guest
//! round trip (`getfattr`) this pass didn't add.
//!
//! `ListDir`'s `depth` field has no documented semantics in the proto
//! itself; this treats `0` and `1` the same (immediate children only) and
//! `depth = N > 1` as `find -maxdepth N`, which is the most literal reading
//! available without a reference implementation to check against.

use std::sync::Arc;
use std::time::Duration;

use tonic::{Request, Response, Status};

use hv2_agent::AgentVM;

pub mod filesystem_proto {
    // Generated by prost from filesystem.proto. The lints apply to code
    // nobody here writes or can fix, and `-D warnings` in the sweep turns one
    // into a build failure for the whole workspace: prost lays `Event` out
    // with a large variant, which is the wire format's shape, not a choice.
    #![allow(clippy::large_enum_variant, clippy::doc_overindented_list_items)]

    tonic::include_proto!("filesystem");
}

use filesystem_proto::filesystem_server::Filesystem;
pub use filesystem_proto::filesystem_server::FilesystemServer;
use filesystem_proto::{
    CreateWatcherRequest, CreateWatcherResponse, EntryInfo, FileType, GetWatcherEventsRequest,
    GetWatcherEventsResponse, ListDirRequest, ListDirResponse, MakeDirRequest, MakeDirResponse,
    MoveRequest, MoveResponse, RemoveRequest, RemoveResponse, RemoveWatcherRequest,
    RemoveWatcherResponse, StatRequest, StatResponse, WatchDirRequest, WatchDirResponse,
};

const EXEC_TIMEOUT: Duration = Duration::from_secs(10);

/// One VM's `filesystem.Filesystem` service.
pub struct EnvdFilesystem {
    vm: Arc<AgentVM>,
}

impl EnvdFilesystem {
    pub fn new(vm: Arc<AgentVM>) -> Self {
        Self { vm }
    }

    /// `stat` (mode/size/owner/group/mtime) plus `readlink`, in one guest
    /// round trip, for `path`. Returns `Ok(None)` if the path does not
    /// exist (a `Status::not_found` case, not an error the caller needs
    /// the raw guest error text for).
    async fn stat_entry(&self, path: &str) -> Result<Option<EntryInfo>, Status> {
        // Single quotes around `path` -- a path containing one would break
        // this, which is a real limitation of shelling out rather than
        // using a syscall directly, stated rather than hidden.
        //
        // `|| true` on the final command matters: `readlink` on anything
        // that isn't a symlink exits non-zero by design (that's how "not a
        // symlink" is reported), and it's the last command in the script,
        // so its exit status would otherwise become the *whole script's*
        // reported exit code -- read as "stat failed" by the check below,
        // for a stat that had already succeeded. Found by reproducing this
        // exact script by hand and seeing exit 1 with empty stderr on an
        // ordinary directory, not the sentinel 17 a real stat failure
        // produces.
        let script = format!(
            "stat -c '%f|%s|%a|%U|%G|%Y' '{path}' 2>/dev/null || exit 17; \
             echo ---; readlink '{path}' 2>/dev/null || true"
        );
        let exec = self
            .vm
            .exec_in_guest("/bin/sh", &["-c".to_string(), script], EXEC_TIMEOUT)
            .await
            .map_err(|e| Status::internal(format!("exec_in_guest: {e}")))?;

        if exec.exit_code == Some(17) {
            return Ok(None);
        }
        if exec.exit_code != Some(0) {
            return Err(Status::internal(format!(
                "stat failed: exit {:?}, stderr {:?}",
                exec.exit_code, exec.stderr
            )));
        }

        let mut parts = exec.stdout.splitn(2, "---\n");
        let stat_line = parts.next().unwrap_or_default();
        let symlink_target = parts.next().map(str::trim).filter(|s| !s.is_empty());

        let fields: Vec<&str> = stat_line.trim().split('|').collect();
        let [raw_mode_hex, size, perms_octal, owner, group, mtime] = fields.as_slice() else {
            return Err(Status::internal(format!(
                "could not parse stat output: {stat_line:?}"
            )));
        };

        let raw_mode = u32::from_str_radix(raw_mode_hex, 16)
            .map_err(|e| Status::internal(format!("bad mode {raw_mode_hex:?}: {e}")))?;
        // Linux's `st_mode` file-type bits: S_IFMT (0o170000) masks them,
        // S_IFREG=0o100000, S_IFDIR=0o040000, S_IFLNK=0o120000.
        let file_type = match raw_mode & 0o170000 {
            0o100000 => FileType::File,
            0o040000 => FileType::Directory,
            0o120000 => FileType::Symlink,
            _ => FileType::Unspecified,
        };

        let name = path.rsplit('/').next().unwrap_or(path).to_string();
        let size: i64 = size
            .parse()
            .map_err(|e| Status::internal(format!("bad size {size:?}: {e}")))?;
        let mode: u32 = raw_mode & 0o7777;
        let mtime_secs: i64 = mtime
            .parse()
            .map_err(|e| Status::internal(format!("bad mtime {mtime:?}: {e}")))?;

        Ok(Some(EntryInfo {
            name,
            r#type: file_type as i32,
            path: path.to_string(),
            size,
            mode,
            permissions: (*perms_octal).to_string(),
            owner: (*owner).to_string(),
            group: (*group).to_string(),
            modified_time: Some(prost_types::Timestamp {
                seconds: mtime_secs,
                nanos: 0,
            }),
            symlink_target: symlink_target.map(str::to_string),
            // See this module's doc comment: reading xattrs would need
            // another guest round trip (getfattr) not added in this pass.
            metadata: Default::default(),
        }))
    }

    async fn require_entry(&self, path: &str) -> Result<EntryInfo, Status> {
        self.stat_entry(path)
            .await?
            .ok_or_else(|| Status::not_found(format!("no such path: {path}")))
    }
}

#[tonic::async_trait]
impl Filesystem for EnvdFilesystem {
    type WatchDirStream = std::pin::Pin<
        Box<dyn tokio_stream::Stream<Item = Result<WatchDirResponse, Status>> + Send>,
    >;

    async fn stat(&self, request: Request<StatRequest>) -> Result<Response<StatResponse>, Status> {
        let path = request.into_inner().path;
        let entry = self.require_entry(&path).await?;
        Ok(Response::new(StatResponse { entry: Some(entry) }))
    }

    async fn make_dir(
        &self,
        request: Request<MakeDirRequest>,
    ) -> Result<Response<MakeDirResponse>, Status> {
        let path = request.into_inner().path;
        let script = format!("mkdir -p '{path}'");
        let exec = self
            .vm
            .exec_in_guest("/bin/sh", &["-c".to_string(), script], EXEC_TIMEOUT)
            .await
            .map_err(|e| Status::internal(format!("exec_in_guest: {e}")))?;
        if exec.exit_code != Some(0) {
            return Err(Status::internal(format!(
                "mkdir failed: exit {:?}, stderr {:?}",
                exec.exit_code, exec.stderr
            )));
        }
        let entry = self.require_entry(&path).await?;
        Ok(Response::new(MakeDirResponse { entry: Some(entry) }))
    }

    async fn r#move(
        &self,
        request: Request<MoveRequest>,
    ) -> Result<Response<MoveResponse>, Status> {
        let req = request.into_inner();
        let script = format!("mv '{}' '{}'", req.source, req.destination);
        let exec = self
            .vm
            .exec_in_guest("/bin/sh", &["-c".to_string(), script], EXEC_TIMEOUT)
            .await
            .map_err(|e| Status::internal(format!("exec_in_guest: {e}")))?;
        if exec.exit_code != Some(0) {
            return Err(Status::internal(format!(
                "mv failed: exit {:?}, stderr {:?}",
                exec.exit_code, exec.stderr
            )));
        }
        let entry = self.require_entry(&req.destination).await?;
        Ok(Response::new(MoveResponse { entry: Some(entry) }))
    }

    async fn remove(
        &self,
        request: Request<RemoveRequest>,
    ) -> Result<Response<RemoveResponse>, Status> {
        let path = request.into_inner().path;
        let script = format!("rm -rf '{path}'");
        let exec = self
            .vm
            .exec_in_guest("/bin/sh", &["-c".to_string(), script], EXEC_TIMEOUT)
            .await
            .map_err(|e| Status::internal(format!("exec_in_guest: {e}")))?;
        if exec.exit_code != Some(0) {
            return Err(Status::internal(format!(
                "rm failed: exit {:?}, stderr {:?}",
                exec.exit_code, exec.stderr
            )));
        }
        Ok(Response::new(RemoveResponse {}))
    }

    async fn list_dir(
        &self,
        request: Request<ListDirRequest>,
    ) -> Result<Response<ListDirResponse>, Status> {
        let req = request.into_inner();
        // See this module's doc comment: 0 and 1 both mean "immediate
        // children only," since the proto documents no semantics to check
        // against.
        let max_depth = req.depth.max(1);
        let script = format!(
            "find '{}' -mindepth 1 -maxdepth {} -print",
            req.path, max_depth
        );
        let exec = self
            .vm
            .exec_in_guest("/bin/sh", &["-c".to_string(), script], EXEC_TIMEOUT)
            .await
            .map_err(|e| Status::internal(format!("exec_in_guest: {e}")))?;
        if exec.exit_code != Some(0) {
            return Err(Status::internal(format!(
                "find failed: exit {:?}, stderr {:?}",
                exec.exit_code, exec.stderr
            )));
        }

        let mut entries = Vec::new();
        for line in exec.stdout.lines().filter(|l| !l.is_empty()) {
            if let Some(entry) = self.stat_entry(line).await? {
                entries.push(entry);
            }
            // A path `find` just reported but that vanished before `stat`
            // could see it (a real race, not a bug in either command) is
            // silently omitted rather than turned into an error for the
            // whole listing.
        }
        Ok(Response::new(ListDirResponse { entries }))
    }

    async fn watch_dir(
        &self,
        _request: Request<WatchDirRequest>,
    ) -> Result<Response<Self::WatchDirStream>, Status> {
        Err(Status::unimplemented(
            "watching needs a long-lived guest-side watcher reporting over a channel this \
             design doesn't have yet",
        ))
    }

    async fn create_watcher(
        &self,
        _request: Request<CreateWatcherRequest>,
    ) -> Result<Response<CreateWatcherResponse>, Status> {
        Err(Status::unimplemented("watching is not implemented"))
    }

    async fn get_watcher_events(
        &self,
        _request: Request<GetWatcherEventsRequest>,
    ) -> Result<Response<GetWatcherEventsResponse>, Status> {
        Err(Status::unimplemented("watching is not implemented"))
    }

    async fn remove_watcher(
        &self,
        _request: Request<RemoveWatcherRequest>,
    ) -> Result<Response<RemoveWatcherResponse>, Status> {
        Err(Status::unimplemented("watching is not implemented"))
    }
}
