//! A real implementation of envd's `process.Process` gRPC service, against
//! the actual proto copied from `e2b-dev/runtime`'s
//! `packages/envd/spec/process/process.proto` (see `proto/process.proto`).
//!
//! Every RPC but `Update` is backed by a real process in the guest. The guest
//! agent starts a program and keeps it (`Operation::Start`), so this module
//! holds something that is still running: `Start` streams output as it
//! arrives, `Connect` reattaches to it, `SendInput` / `StreamInput` write to
//! its stdin, `CloseStdin` sends EOF, and `SendSignal` signals it. `pid` is
//! the guest's own pid throughout -- not a synthetic id, as it was while
//! this was built on `exec_in_guest`.
//!
//! `Update` is PTY resize, and stays `unimplemented`: there is no PTY. The
//! guest agent gives a program three pipes, so there is no terminal to
//! resize, and reporting success would be a lie. For the same reason
//! `DataEvent::pty` is never emitted and `ProcessInput::pty` is refused.
//!
//! Output is *polled* from the guest rather than pushed: the agent buffers
//! what a program prints and this module drains it every `POLL_INTERVAL`.
//! So "as it arrives" means within that interval, not instantly. One poller
//! per process publishes to a broadcast channel, which is what lets `Start`
//! and any number of `Connect`s watch the same process without stealing each
//! other's output -- a poll drains, so two independent pollers would each see
//! half of it.
//!
//! A `Connect` sees what happens *from then on*. Output a process produced
//! before the reattach is gone: it was drained and delivered to whoever was
//! watching at the time, and this module keeps no scrollback.
//!
//! `List` reflects genuinely in-flight work -- a process is registered when
//! it starts and removed when its poller sees it exit.
//!
//! Served on both gRPC and the Connect protocol, on one port per sandbox --
//! see [`crate::connect`], which is where E2B's own SDK is answered, and why
//! this struct is `Clone`.
//!
//! Pulled out of the `envd_process` example and into the crate itself so
//! both that example (one VM, one daemon, matching envd's real per-sandbox
//! shape) and `e2b_compat`'s per-sandbox gRPC listener (see
//! `serve_for_sandbox`) share one implementation rather than diverging.

use std::collections::HashMap;
use std::pin::Pin;
use std::sync::Arc;
use std::time::Duration;

use parking_lot::Mutex;
use tokio::sync::broadcast;
use tokio_stream::{Stream, StreamExt};
use tonic::{Request, Response, Status};

use hv2_agent::AgentVM;

pub mod process_proto {
    // As in `envd_filesystem`: generated code, lints nobody can act on.
    #![allow(clippy::large_enum_variant, clippy::doc_overindented_list_items)]

    tonic::include_proto!("process");

    // Protobuf-JSON for these same types, generated by pbjson-build in
    // this crate's build script. What the Connect protocol's JSON codec
    // needs; see `crate::connect`.
    include!(concat!(env!("OUT_DIR"), "/process.serde.rs"));
}

use process_proto::process_event::{DataEvent, EndEvent, Event as ProcessEventKind, StartEvent};
use process_proto::process_server::Process;
pub use process_proto::process_server::ProcessServer;
use process_proto::{
    CloseStdinRequest, CloseStdinResponse, ConnectRequest, ConnectResponse, ListRequest,
    ListResponse, ProcessEvent, ProcessInfo, ProcessSelector, SendInputRequest, SendInputResponse,
    SendSignalRequest, SendSignalResponse, StartRequest, StartResponse, StreamInputRequest,
    StreamInputResponse, UpdateRequest, UpdateResponse,
};

/// How often a running process is drained.
///
/// This is latency the client sees on every byte, so it wants to be small; it
/// is also a round trip over vsock per running process, so it cannot be tiny.
/// 50ms is below the point where a human notices output lagging their input,
/// and costs 20 round trips a second for a process nobody is watching.
const POLL_INTERVAL: Duration = Duration::from_millis(50);

/// How long any single guest-agent call may take before it counts as failed.
const GUEST_TIMEOUT: Duration = Duration::from_secs(10);

/// How many events a slow watcher may fall behind before it starts losing
/// them. A watcher this far behind is not keeping up with the process, and
/// buffering without limit would grow until the host is out of memory.
const EVENT_BACKLOG: usize = 256;

/// A process this service started and has not yet seen exit.
struct Tracked {
    info: ProcessInfo,
    /// Everything its poller has published. `Start` and every `Connect`
    /// subscribe here; see this module's doc comment for why a shared
    /// broadcast rather than each caller polling for itself.
    events: broadcast::Sender<ProcessEvent>,
}

/// One VM's `process.Process` service -- envd for exactly the sandbox this
/// was built for, not a multi-sandbox multiplexer.
///
/// Cloning shares the VM and the table of running processes, so one service
/// can answer on both gRPC and Connect without either surface holding
/// processes the other cannot see.
#[derive(Clone)]
pub struct EnvdProcess {
    vm: Arc<AgentVM>,
    /// Guest pid -> the process, for every one currently running.
    running: Arc<Mutex<HashMap<u32, Tracked>>>,
}

impl EnvdProcess {
    pub fn new(vm: Arc<AgentVM>) -> Self {
        Self {
            vm,
            running: Arc::new(Mutex::new(HashMap::new())),
        }
    }

    /// Resolve the pid a request is about.
    ///
    /// The proto lets a caller name a process by pid or by the tag it was
    /// started with, and every RPC below `Start` takes the same selector, so
    /// this is one place rather than six.
    pub(crate) fn resolve(&self, selector: Option<ProcessSelector>) -> Result<u32, Status> {
        use process_proto::process_selector::Selector;

        let selector = selector
            .and_then(|s| s.selector)
            .ok_or_else(|| Status::invalid_argument("a process selector is required"))?;

        match selector {
            Selector::Pid(pid) => {
                if self.running.lock().contains_key(&pid) {
                    Ok(pid)
                } else {
                    Err(Status::not_found(format!(
                        "no running process with pid {pid}"
                    )))
                }
            }
            Selector::Tag(tag) => self
                .running
                .lock()
                .values()
                .find(|t| t.info.tag.as_deref() == Some(tag.as_str()))
                .map(|t| t.info.pid)
                .ok_or_else(|| Status::not_found(format!("no running process tagged {tag}"))),
        }
    }

    /// Subscribe to a running process's events.
    fn watch(&self, pid: u32) -> Result<broadcast::Receiver<ProcessEvent>, Status> {
        self.running
            .lock()
            .get(&pid)
            .map(|t| t.events.subscribe())
            .ok_or_else(|| Status::not_found(format!("no running process with pid {pid}")))
    }

    /// Write to a running process's stdin, translating the proto's input
    /// oneof. Shared by `SendInput` and `StreamInput`.
    pub(crate) async fn write_input(
        &self,
        pid: u32,
        input: Option<process_proto::ProcessInput>,
    ) -> Result<(), Status> {
        use process_proto::process_input::Input;

        let input = input
            .and_then(|i| i.input)
            .ok_or_else(|| Status::invalid_argument("input is required"))?;

        let bytes =
            match input {
                Input::Stdin(bytes) => bytes,
                Input::Pty(_) => return Err(Status::unimplemented(
                    "there is no PTY to write to: the guest agent gives a program pipes, not a \
                     terminal. Send stdin instead",
                )),
            };

        // The guest agent's protocol carries stdin as a string, so input that
        // is not text cannot be passed on. Refusing beats silently replacing
        // bytes the program was going to act on.
        let text = String::from_utf8(bytes)
            .map_err(|_| Status::invalid_argument("stdin must be valid UTF-8"))?;

        self.vm
            .write_stdin_in_guest(pid, &text, false, GUEST_TIMEOUT)
            .await
            .map_err(|e| Status::internal(format!("writing to pid {pid}: {e}")))
    }
}

/// Turn a process's broadcast into a gRPC response stream.
///
/// A watcher that falls `EVENT_BACKLOG` behind is told what it missed
/// rather than silently skipped: losing output without saying so would make a
/// truncated log look complete.
fn stream_of<T, F>(
    rx: broadcast::Receiver<ProcessEvent>,
    wrap: F,
) -> Pin<Box<dyn Stream<Item = Result<T, Status>> + Send>>
where
    T: Send + 'static,
    F: Fn(ProcessEvent) -> T + Send + 'static,
{
    let stream = tokio_stream::wrappers::BroadcastStream::new(rx).map(move |event| match event {
        Ok(event) => Ok(wrap(event)),
        Err(tokio_stream::wrappers::errors::BroadcastStreamRecvError::Lagged(n)) => Err(
            Status::data_loss(format!("this watcher fell behind and lost {n} events")),
        ),
    });
    Box::pin(stream)
}

/// One output event, the long way the generated types spell it.
fn data(output: process_proto::process_event::data_event::Output) -> ProcessEvent {
    ProcessEvent {
        event: Some(ProcessEventKind::Data(DataEvent {
            output: Some(output),
        })),
    }
}

/// Drain a running process until it exits, publishing what it prints.
///
/// One of these per process, spawned by `Start`. It is also what removes the
/// process from the running table, so `List` and the selectors above stop
/// reporting it exactly when it stops existing.
async fn pump(
    vm: Arc<AgentVM>,
    pid: u32,
    running: Arc<Mutex<HashMap<u32, Tracked>>>,
    events: broadcast::Sender<ProcessEvent>,
) {
    use process_proto::process_event::data_event::Output;

    loop {
        match vm.poll_in_guest(pid, GUEST_TIMEOUT).await {
            Ok(output) => {
                if !output.stdout.is_empty() {
                    let _ = events.send(data(Output::Stdout(output.stdout.into_bytes())));
                }
                if !output.stderr.is_empty() {
                    let _ = events.send(data(Output::Stderr(output.stderr.into_bytes())));
                }
                if !output.running {
                    // A signalled process has no exit code of its own. 128+n
                    // is the shell's convention for one, and -1 would be
                    // indistinguishable from the error arm below.
                    let exit_code = output
                        .exit_code
                        .or_else(|| output.signal.map(|s| 128 + s))
                        .unwrap_or(-1);
                    let _ = events.send(ProcessEvent {
                        event: Some(ProcessEventKind::End(EndEvent {
                            exit_code,
                            exited: true,
                            status: if output.signal.is_some() {
                                "signalled".to_string()
                            } else {
                                "exited".to_string()
                            },
                            error: None,
                        })),
                    });
                    break;
                }
            }
            Err(e) => {
                let _ = events.send(ProcessEvent {
                    event: Some(ProcessEventKind::End(EndEvent {
                        exit_code: -1,
                        exited: false,
                        status: "error".to_string(),
                        error: Some(e.to_string()),
                    })),
                });
                break;
            }
        }
        tokio::time::sleep(POLL_INTERVAL).await;
    }

    running.lock().remove(&pid);
}

#[tonic::async_trait]
impl Process for EnvdProcess {
    type ConnectStream = Pin<Box<dyn Stream<Item = Result<ConnectResponse, Status>> + Send>>;
    type StartStream = Pin<Box<dyn Stream<Item = Result<StartResponse, Status>> + Send>>;

    async fn list(&self, _request: Request<ListRequest>) -> Result<Response<ListResponse>, Status> {
        let processes = self
            .running
            .lock()
            .values()
            .map(|t| t.info.clone())
            .collect();
        Ok(Response::new(ListResponse { processes }))
    }

    async fn connect(
        &self,
        request: Request<ConnectRequest>,
    ) -> Result<Response<Self::ConnectStream>, Status> {
        let pid = self.resolve(request.into_inner().process)?;
        let rx = self.watch(pid)?;
        Ok(Response::new(stream_of(rx, |event| ConnectResponse {
            event: Some(event),
        })))
    }

    async fn start(
        &self,
        request: Request<StartRequest>,
    ) -> Result<Response<Self::StartStream>, Status> {
        let req = request.into_inner();
        let config = req
            .process
            .ok_or_else(|| Status::invalid_argument("process config is required"))?;

        if req.pty.is_some() {
            return Err(Status::unimplemented(
                "a PTY was requested, but the guest agent starts programs with pipes and has no \
                 terminal to give them. Start without one",
            ));
        }
        if !config.envs.is_empty() {
            // Accepting and dropping them would leave a program running
            // without the environment it was told it had, failing later for a
            // reason nothing points at.
            return Err(Status::unimplemented(
                "per-process environment variables are not implemented: the guest agent's start \
                 operation carries a program, its arguments and a working directory only",
            ));
        }

        let pid = self
            .vm
            .start_in_guest(
                &config.cmd,
                &config.args,
                config.cwd.as_deref(),
                GUEST_TIMEOUT,
            )
            .await
            .map_err(|e| Status::internal(format!("starting {}: {e}", config.cmd)))?;

        let (events, rx) = broadcast::channel(EVENT_BACKLOG);

        // Into the channel before the poller runs, so the caller's stream
        // opens with it -- the proto's first event for a process is its
        // StartEvent, and a client reading the pid from it would otherwise
        // race the first line of output.
        let _ = events.send(ProcessEvent {
            event: Some(ProcessEventKind::Start(StartEvent { pid })),
        });

        self.running.lock().insert(
            pid,
            Tracked {
                info: ProcessInfo {
                    config: Some(config),
                    pid,
                    tag: req.tag,
                },
                events: events.clone(),
            },
        );

        tokio::spawn(pump(
            Arc::clone(&self.vm),
            pid,
            Arc::clone(&self.running),
            events,
        ));

        Ok(Response::new(stream_of(rx, |event| StartResponse {
            event: Some(event),
        })))
    }

    async fn update(
        &self,
        _request: Request<UpdateRequest>,
    ) -> Result<Response<UpdateResponse>, Status> {
        Err(Status::unimplemented(
            "PTY resize is not implemented: a process started here has pipes, not a terminal, so \
             there is nothing with a size to change",
        ))
    }

    async fn stream_input(
        &self,
        request: Request<tonic::Streaming<StreamInputRequest>>,
    ) -> Result<Response<StreamInputResponse>, Status> {
        use process_proto::stream_input_request::Event;

        let mut inbound = request.into_inner();

        // The first message names the process; the rest are input for it.
        // Ordering is the reason this RPC exists at all, so the pid is
        // resolved once here rather than per message -- a process that exits
        // mid-stream should fail the writes, not silently rebind to whatever
        // else answers to the same tag.
        let mut pid: Option<u32> = None;

        while let Some(message) = inbound.next().await {
            let message = message?;
            match message.event {
                Some(Event::Start(start)) => {
                    pid = Some(self.resolve(start.process)?);
                }
                Some(Event::Data(payload)) => {
                    let pid = pid.ok_or_else(|| {
                        Status::failed_precondition(
                            "the first message on this stream must name the process",
                        )
                    })?;
                    self.write_input(pid, payload.input).await?;
                }
                Some(Event::Keepalive(_)) | None => {}
            }
        }

        Ok(Response::new(StreamInputResponse {}))
    }

    async fn send_input(
        &self,
        request: Request<SendInputRequest>,
    ) -> Result<Response<SendInputResponse>, Status> {
        let req = request.into_inner();
        let pid = self.resolve(req.process)?;
        self.write_input(pid, req.input).await?;
        Ok(Response::new(SendInputResponse {}))
    }

    async fn send_signal(
        &self,
        request: Request<SendSignalRequest>,
    ) -> Result<Response<SendSignalResponse>, Status> {
        use process_proto::Signal;

        let req = request.into_inner();
        let pid = self.resolve(req.process)?;

        let signal = match Signal::try_from(req.signal) {
            Ok(Signal::Sigterm) => GUEST_SIGTERM,
            Ok(Signal::Sigkill) => GUEST_SIGKILL,
            Ok(Signal::Unspecified) | Err(_) => {
                return Err(Status::invalid_argument(
                    "signal must be SIGNAL_SIGTERM or SIGNAL_SIGKILL",
                ))
            }
        };

        self.vm
            .signal_in_guest(pid, signal, GUEST_TIMEOUT)
            .await
            .map_err(|e| Status::internal(format!("signalling pid {pid}: {e}")))?;

        Ok(Response::new(SendSignalResponse {}))
    }

    async fn close_stdin(
        &self,
        request: Request<CloseStdinRequest>,
    ) -> Result<Response<CloseStdinResponse>, Status> {
        let pid = self.resolve(request.into_inner().process)?;
        self.vm
            .write_stdin_in_guest(pid, "", true, GUEST_TIMEOUT)
            .await
            .map_err(|e| Status::internal(format!("closing stdin for pid {pid}: {e}")))?;
        Ok(Response::new(CloseStdinResponse {}))
    }
}

/// The guest's signal numbers, not this host's.
///
/// Written out rather than taken from `libc` because the host may not be
/// Linux at all, while these always travel to a Linux guest. Both are fixed
/// across every Linux architecture this runs on.
const GUEST_SIGTERM: i32 = 15;
const GUEST_SIGKILL: i32 = 9;

/// Serve `process.Process` **and** `filesystem.Filesystem` for `vm` on
/// `addr`, until `shutdown` fires -- both on the same port, the way real
/// envd does. One call to this is one sandbox's whole envd, matching its
/// real per-sandbox-daemon shape -- see this module's own doc comment.
///
/// Speaks gRPC *and* the Connect protocol on that one port, because the two
/// clients that matter disagree about which to use: `grpcurl` sends gRPC, and
/// E2B's own SDK sends Connect. They share every path, so [`crate::connect`]
/// tells them apart by content-type.
///
/// # Errors
///
/// Fails if `addr` cannot be bound.
pub async fn serve_for_sandbox(
    vm: Arc<AgentVM>,
    addr: std::net::SocketAddr,
    shutdown: tokio::sync::oneshot::Receiver<()>,
) -> std::io::Result<()> {
    crate::connect::serve(vm, addr, shutdown).await
}
